#配置服务器的相关参数
#server:
#  port: 8081





#配置过滤器的相关参数
filter:
  exclusion: "*.js,*.css,/druid/*"
druid:
  mysql:
    usePingMethod: false
#配置数据源的相关参数（druid数据源）
spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 717717
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #配置邮件发送功能

    #  spring.mail.host=smtp.qq.com
    #  spring.mail.port=587
    #  spring.mail.username=1510161612@qq.com
    #  spring.mail.password=ubknfzhjkhrbbabe
    #  spring.mail.default-encoding=UTF-8
    #spring.mail.properties.mail.smtp.socketFactoryClass=javax.net.ssl.SSLSocketFactory
    #spring.mail.properties.mail.debug=true
  mail:
    host: smtp.qq.com
    port: 587
    username: 846047475@qq.com
    password: bqilqhblhdlvbbeb
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory
      mail.smtp.debug: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  #  #配置模板引擎
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#      #当static文件夹下还有文件夹时，访问时，需要该配置，否则访问不到
#    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

#   程序启动自动创建数据表
#   schema:
#这里不知道为什么classpath:后需要加一个空格才能生效
#      - classpath: sql/department.sql
#      - classpath: sql/employee.sql
#    initialization-mode: always




